config/routes.rb
Rails.application.routes.draw do
  # get 'restaurants/index'
  resources :restaurants do
    resources :reviews, only: [ :show, :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true

  validates :rating, presence: true, numericality: { only_integer: true }
  validates :rating, inclusion: 0..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  def show
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Yelp Mvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #f5f5f4">
    <%= render 'restaurants/header' %>
    <div class="container mt-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid mt-2">
    <%= link_to '🍴Restaurants', restaurants_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'New Restaurant', new_restaurant_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/restaurants/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">🍴All Restaurants 🍱🌮🍔</h1>
  <% @restaurants.each do |restaurant| %>
      <hr class="my-4">
      <p class="lead"><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
      <p class="text-right" style="color: #e53964"><%= restaurant.category %> </p>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="jumbotron">
  <h2 class="display-4">Add a new restaurant</h2>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.button :submit, class:"btn btn-outline-dark border-success" %>
    <%= link_to 'Back to restaurants', restaurants_path, class:"btn btn-outline-dark border-primary" %>
  <% end %>

</div>

app/views/restaurants/show.html.erb
<div class="jumbotron">
  <h2 class="display-4" style="color: #7e7eff"><%= @restaurant.name %>🍴</h2>
  <p class="lead">Address: <%= @restaurant.address %> </p>
  <p class="lead">Phone: <%= @restaurant.phone_number %> </p>
  <p class="lead" style="color:#e53964"><%= @restaurant.category %> </p>

  <hr class="my-4">
  <h5 style="color: #7e73ff"><strong> <%= link_to 'All Reviews', restaurant_review_path(@restaurant) %></strong></h5>
  <div>
    <% @restaurant.reviews.each do |review| %>
      <div class="ratings"> <span class="product-rating" style="color:#e53964"><%= review.rating %></span><span style="color:#e53964">/5</span>
          <p class="lead"><%= review.content %></p>
      </div>
      <% end %>
  </div>
</div>
<br>
<%= link_to 'Back to restaurants', restaurants_path, class:"btn btn-outline-dark border-primary" %>

<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class:"btn btn-outline-dark border-success" %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
<h2 class="my-4" style="color: #7e73ff"><%= @restaurant.name %></h2>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit a review", class: "btn btn-outline-dark border-success" %>
  <%= link_to 'Back to restaurant', restaurant_path(@restaurant), class:"btn btn-outline-dark border-primary" %>
<% end %>

app/views/reviews/show.html.erb
<div class="jumbotron">
  <h2 class="mb-4" style="color: #7e73ff"><%= @restaurant.name %></h2>
  <h5 class="mb-4" style="color: #e53964"><strong>All Reviews</strong></h5>
    <% @restaurant.reviews.each do |review| %>
      <div class="ratings"> <span class="product-rating" style="color:#e53964"><%= review.rating %></span><span style="color:#e53964">/5</span>
          <p class="lead"><%= review.content %></p>
      </div>
      <% end %>
</div>

<%= link_to 'Back to restaurant', restaurant_path, class:"btn btn-outline-dark border-primary" %>
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class:"btn btn-outline-dark border-success" %>